
spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ec_db?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ec_user
    password: ec_user_01
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


server:
  servlet:
    context-path: /ec/api

application:
  security:
    hash:
      algorithm: PBKDF2WithHmacSHA256
      seed: hogehoge
      stretch: 12
    token:
      headerName: X-TOKEN-EC
      prefix: tk_ec_app
      secret: fapw3fei$samale
      expirationTime: 3000
      allowDomain: http://localhost:3000
logging:
  level:
    root: info
