@startuml
left to right direction
skinparam packageStyle rectangle

rectangle 取引プロセス {
  (<<交換プロセス>>\n販売) ..> (<<交換プロセス>>\n購入) : 現金
  (<<交換プロセス>>\n購入) ..> (<<交換プロセス>>\n商品の掲載) : 製造
  (<<交換プロセス>>\n購入) .> (<<交換プロセス>>\n手数料の取得): 現金
  (<<交換プロセス>>\n手数料の取得) ..> (<<交換プロセス>>\n商品の掲載): サイト向上
  (<<交換プロセス>>\n商品の掲載) ..> (<<交換プロセス>>\n販売) : 商品

}
@enduml
