@startmindmap
* ECサイト
** 出品者用ログイン
*** 商品登録
*** チャット一覧
**** チャット画面
*** 商品情報変更
** 購入者用ログイン
*** 商品検索
**** 商品詳細
***** 商品購入
****** 商品決済
******* 商品決済完了
*** 商品購入
**** 商品決済
***** 商品決済完了
*** カート一覧
**** 商品購入
***** 商品決済
****** 商品決済完了
*** お気に入り一覧
**** カートに入れる

@endmindmap
