@startuml
left to right direction
skinparam packageStyle rectangle

rectangle パスワードリマインダー {
  (パスワード忘れた) ..> (リマインダー画面) : メールアドレス
  (リマインダー画面) ..> (パスワード変更用メール送信) : メールアドレス
  (リマインダー画面) ..> (パスワード変更用メール送信) : メールアドレス
  (パスワード変更用メール送信) ..> (パスワード変更用リンク_通常): eg
  (パスワード変更用リンク_通常) ..> (パスワードの変更) : 新規パスワードの入力
  (パスワードの変更) ..> (パスワードの完了) : ログインへ
  ((パスワード変更用リンク_通常) ..> (パスワードの変更ロック) : 旧パスワードの入力
  (パスワードの変更ロック) ..> (アカウントロック) : Web
  (パスワードの変更ロック) ..> (アカウントロック): 電話

  (パスワード変更_二段階認証) ..> (パスコード入力画面) : パスコードの入力
  (パスコード入力画面) ..> (パスワードの変更) : パスワード入力
  (パスワードの変更) ..> (パスワード変更完了)
}
@enduml
