@startuml


interface User{
 リセット要求: ログインできたら解除？
}

interface Password_Reminder_Mailer{
有効期限
トークン
キー
ソルト
}


interface TwoFactorAuthenticator
class SMSAuthenticator
class TelAuthenticator

User<|-- Password_Reminder_Mailer
Password_Reminder_Mailer <|-- TwoFactorAuthenticator

TwoFactorAuthenticator<|-- TelAuthenticator
TwoFactorAuthenticator<|-- SMSAuthenticator

@enduml
